logging:
  level:
    org:
      springframework:
        cloud:
          task: DEBUG
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # Work around for https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: expense-loader
  datasource:
    url: ${CM_postgres_url:jdbc:postgresql://localhost:5432/springbootdb}
    username: ${CM_postgres_user:springboot}
    password: ${CM_postgres_password:password}
